version: "3.7"
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "letmein"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
      MYSQL_DATABASE: "persons"