apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: agile-springboot
deploy:
  kubectl:
    manifests:
    - src\main\kubernetes\agile-springboot.yml
    - src\main\kubernetes\mysql.yml
