apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:5.6  # or just image: redis
          ports:
            - containerPort: 3306