spring:
  profiles: generic
  datasource:
    url: jdbc:mysql://192.168.99.106/persons
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  profiles: docker
    include: generic
    datasource:
      url: jdbc:mysql://mysql/persons